namespace Loupedeck.MsfsPlugin
{
    public enum BindingKeys
    {
        ENGINE_AUTO,
        KOHLSMAN,
        AILERON_TRIM,
        ELEVATOR_TRIM,
        RUDDER_TRIM,
        AP_ALT,
        ALT,
        MAX_FLAP,
        FLAP,
        AP_HEADING,
        HEADING,
        MIXTURE,
        PROPELLER,
        AP_SPEED,
        SPEED,
        SPOILER,
        MIN_THROTTLE,
        THROTTLE,
        AP_VSPEED,
        VSPEED,
        PARKING_BRAKES,
        PAUSE,
        PITOT,
        CONNECTION,
    }
}
