<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <OutputType>Library</OutputType>
    <Nullable>warnings</Nullable>
    <RootNamespace>Loupedeck.MsfsPlugin</RootNamespace>
    <FileAlignment>512</FileAlignment>
    <ErrorReport>prompt</ErrorReport>
    <WarningLevel>4</WarningLevel>

    <AppendTargetFrameworkToOutputPath>false</AppendTargetFrameworkToOutputPath>
    <CopyLocalLockFileAssemblies>true</CopyLocalLockFileAssemblies>

    <PluginApiDir Condition="$(OS) == 'Windows_NT'">C:\Program Files\Logi\LogiPluginService\</PluginApiDir>
    <PluginDir Condition="$(OS) == 'Windows_NT'">$(LocalAppData)\Logi\LogiPluginService\Plugins\</PluginDir>

    <SignAssembly>False</SignAssembly>
    <PlatformTarget>x64</PlatformTarget>
  </PropertyGroup>

  <PropertyGroup Condition="'$(Configuration)|$(Platform)'=='Debug|AnyCPU'">
    <Optimize>False</Optimize>
    <GenerateAssemblyInfo>False</GenerateAssemblyInfo>
  </PropertyGroup>

  <PropertyGroup Condition="'$(Configuration)|$(Platform)'=='Release|AnyCPU'">
    <GenerateAssemblyInfo>False</GenerateAssemblyInfo>
  </PropertyGroup>

  <ItemGroup>
    <None Remove="Resources\DefaultProfile20win.lp5" />
    <None Remove="Resources\DefaultProfile30win.lp5" />
    <None Remove="Resources\DefaultProfile40win.lp5" />
    <None Remove="Resources\DefaultProfile50win.lp5" />
    <None Remove="Resources\msfs2020_eventids.cip" />
  </ItemGroup>


  <ItemGroup>
    <EmbeddedResource Include="Resources\16.png" />
    <EmbeddedResource Include="Resources\256.png" />
    <EmbeddedResource Include="Resources\32.png" />
    <EmbeddedResource Include="Resources\48.png" />
    <EmbeddedResource Include="Resources\available.png" />
    <EmbeddedResource Include="Resources\availableBorder.png" />
    <EmbeddedResource Include="Resources\availableFull.png" />
    <EmbeddedResource Include="Resources\DefaultProfile20win.lp5" />
    <EmbeddedResource Include="Resources\DefaultProfile30win.lp5" />
    <EmbeddedResource Include="Resources\DefaultProfile40win.lp5" />
    <EmbeddedResource Include="Resources\DefaultProfile50win.lp5" />
    <EmbeddedResource Include="Resources\disable.png" />
    <EmbeddedResource Include="Resources\disableBorder.png" />
    <EmbeddedResource Include="Resources\disableFull.png" />
    <EmbeddedResource Include="Resources\disconnect.png" />
    <EmbeddedResource Include="Resources\disconnectFull.png" />
    <EmbeddedResource Include="Resources\msfs2020_eventids.cip" />
    <EmbeddedResource Include="Resources\off.png" />
    <EmbeddedResource Include="Resources\offFull.png" />
    <EmbeddedResource Include="Resources\on.png" />
    <EmbeddedResource Include="Resources\onBorder.png" />
    <EmbeddedResource Include="Resources\onFull.png" />
    <EmbeddedResource Include="Resources\trying.png" />
    <EmbeddedResource Include="Resources\tryingFull.png" />
    <EmbeddedResource Include="Resources\wait.png" />
    <EmbeddedResource Include="Resources\waitFull.png" />
  </ItemGroup>

  <ItemGroup>
    <Reference Include="PluginApi">
      <HintPath>$(PluginApiDir)PluginApi.dll</HintPath>
    </Reference>
  </ItemGroup>
  <ItemGroup>
    <Reference Include="nunit.framework, Version=4.0.1.0, Culture=neutral, PublicKeyToken=2638cd05610744eb, processorArchitecture=MSIL">
      <HintPath>..\packages\NUnit.4.0.1\lib\net462\nunit.framework.dll</HintPath>
    </Reference>
    <Reference Include="nunit.framework.legacy, Version=4.0.1.0, Culture=neutral, PublicKeyToken=2638cd05610744eb, processorArchitecture=MSIL">
      <HintPath>..\packages\NUnit.4.0.1\lib\net462\nunit.framework.legacy.dll</HintPath>
    </Reference>
  </ItemGroup>
  <ItemGroup>
    <None Update="Resources\Microsoft.FlightSimulator.SimConnect.dll">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
  </ItemGroup>
 
  <Target Name="PostBuild" AfterTargets="PostBuildEvent">
    <Exec Condition="$(OS) == 'Windows_NT'" Command="echo $(OutputPath) &gt; &quot;$(PluginDir)$(ProjectName).link&quot;" />
    
  </Target>

  <Target Name="CopyMetadata" AfterTargets="PostBuildEvent">
    <ItemGroup>
      <MetadataFiles Include="metadata\*.*" />
    </ItemGroup>
    <Copy SourceFiles="@(MetadataFiles)" DestinationFolder="$(OutputPath)metadata" />
  </Target>

  <Target Name="PluginClean" AfterTargets="CoreClean">
    <Delete Condition="$(OS) == 'Windows_NT'" Files="$(PluginDir)$(ProjectName).link" />
    <RemoveDir Directories="$(OutputPath)metadata" />
  </Target>

</Project>
